version: '3'
services:
  nginx:
    image: jwilder/nginx-proxy:latest
    ports:
      - "3080:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    environment:
      - DEFAULT_HOST=anointan.example

  app: 
    build: ./app
    ports:
      - "8080"
    environment:
      - VIRTUAL_HOST=anointan.example

    restart: always
        
